x = 5
print(type(x))
x = str("Hello World")
x = int(20)
x = float(20.5)
print(type(x))
x = complex(1j)
print(type(n))
c = ("Nev", "Haze", "Rome", "Remekedzo")
print(len(c))
print(c(0))
print(0)
x = list(("apple", "banana", "cherry"))
x = tuple(("apple", "banana", "cherry"))
x = range(6)
x = dict(name="John", age=36)
x = set(("apple", "banana", "cherry"))
x = frozenset(("apple", "banana", "cherry"))
x = bool(5)
x = bytes(5)
x = bytearray(5)
x = memoryview(byte)

message = "Nev is blessed"
print(message)
